---

- name: Add config file
  template: src=shipper_conf.j2 dest={{ logstash_home }}/logstash_shipper.conf owner={{ logstash_user }} group={{ logstash_group }} mode=0644

- name: Add init file
  template: src=shipper_init_conf.j2 dest=/etc/init/logstash-shipper.conf owner=root group=root mode=0644

- name: Create and Make sure log file exists
  file: path={{ logstash_log_dir }}/logstash.log owner={{ logstash_user }} group={{ logstash_group }} mode=0644 state=touch

- name: Start logstash-shipper Service
  service: name=logstash-shipper enabled=yes state=started



