---
#Create webtier instances
- name: Create nodes for web tier in zone a
  ec2:
    instance_type: "{{ web_size }}"
    region: "{{ aws_region }}"
    image: "{{ web_ami }}"
    key_name: "{{ aws_key_name }}"
    vpc_subnet_id: "{{ aws_web_subnet_1a }}"
    group: "['{{ env_prefix }}-SG{{ project_prefix }}Web','{{ web_group_a }}']"
    instance_tags:
      env: "{{ env_prefix }}"
      Name: "{{ env_prefix }}:{{ project_prefix }}:web:{{ env_num }}:a"
      role: webtier
    exact_count: "{{ web_count_1a }}"
    count_tag:
       Name: "{{ env_prefix }}:{{ project_prefix}}:web:{{ env_num }}:a"
       role: webtier
  register: ec2web_a
  when: web_serv  
  tags:
    - webservers

- name: Create nodes for web tier in zone b
  ec2:
    instance_type: "{{ web_size }}"
    region: "{{ aws_region }}"
    image: "{{ web_ami }}"
    key_name: "{{ aws_key_name }}"
    vpc_subnet_id: "{{ aws_web_subnet_1b }}"
    group: "['{{ env_prefix }}-SG{{project_prefix}}Web','{{ web_group_b }}']"
    instance_tags:
      env: "{{ env_prefix }}"
      Name: "{{ env_prefix }}:{{ project_prefix }}:web:{{ env_num }}:b"
      role: webtier
    exact_count: "{{ web_count_1b }}"
    count_tag:
      Name: "{{ env_prefix }}:{{ project_prefix}}:web:{{ env_num }}:b"
      role: webtier
  register: ec2web_b
  when: web_serv  
  tags:
    - webservers
