---
- hosts: jenkins-slaves-{{ env }}
  connection: local
  gather_facts: False
  tags: aws
  vars:
    - jenkins_master_eip: 54.72.74.5
    - jenkins_master_private_ip: 10.50.135.210
  vars_files:
    - aws_{{ env }}_env.yml
  tasks:
    - name: Create security group for the jenkins slaves
      local_action:
        module: ec2_group
        name: "{{ sg }}"
        description: Access to the jenkins slaves
        vpc_id: "{{ vpc }}"
        region: "{{ region }}"
        rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ jenkins_master_eip }}/32"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ jenkins_master_private_ip }}/32"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ jump_a }}/32"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ jump_b }}/32"

    - name: Create the instance for the jenkins slave
      local_action:
        module: ec2
        keypair: "{{ key }}"
        group: "{{ sg }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
        wait: yes
        count_tag:
          Name: "{{ name }}"
        exact_count: 1
        instance_tags:
          Name: "{{ name }}"
          env: "{{ aws_env }}"
          role: jenkins-slave
      register: ec2_jenkins_slave

    - name: Register the instance on route 53
      local_action:
        module: route53
        command: create
        overwrite: yes
        zone: "{{ key }}.api.bskyb.com"
        record: "{{ inventory_hostname_short }}.{{ key }}.api.bskyb.com"
        type: A
        ttl: 300
        value: "{{ item.public_ip }}"
      with_items: ec2_jenkins_slave.tagged_instances

    - name: Wait for the EC2 instance to be accesible via SSH
      pause: seconds=120
